### ISSUE TITLE
Plugin not working with "typedoc": "^0.27.1"

### ISSUE THREAD

**Issue by mayank1513** [tgreyuk/typedoc-plugin-inline-sources#6]
Here is the error message.

[error] The plugin typedoc-plugin-inline-sources could not be loaded
[error] Error [ERR_REQUIRE_ESM]: require() of ES Module `\node_modules\.pnpm\typedoc@0.27.1_typescript@5.7.2\node_modules\typedoc\dist\index.js` from `\node_modules\.pnpm\typedoc-plugin-inline-sources@1.1.0_typedoc@0.27.1_typescript@5.7.2_\node_modules\typedoc-plugin-inline-sources\dist\index.js` not supported

It has to do something with ESM exports please fix.

**Comment by tgreyuk** [comment]
should be fixed in `typedoc-plugin-inline-sources@1.2.0`
